stages:
  prepare:
    cmd: python Labs/Lab03/create_features.py
    deps:
      - data/adult.data
      - data/adult.test
      - Labs/Lab03/create_features.py
    outs:
      - data/pipeline.pkl
      - data/processed_train_data.csv
      - data/processed_test_data.csv

params: 
      - features.chi2percentile
      - features.train_path
      - features.test_path