apiVersion: v1
kind: Service
metadata:
  name: reddit-service
spec:
  selector:
    app: reddit-app
  ports:
    - protocol: TCP
      port: 80       # ← External port
      targetPort: 8000  # ← Matches containerPort
  type: LoadBalancer  # ← Changed from Minikube