apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app
spec:
  selector:
    matchLabels:
      app: reddit-app
  template:
    metadata:
      labels:
        app: reddit-app
    spec:
      containers:
      - name: reddit-app
        image: gcr.io/reddit-app-lab09/reddit-app:v1  # ← Changed from Minikube
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"